### ISSUE TITLE
Error on a 2.4.3 Install

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWireUpgrade#19]
I installed this module and when going to the Upgrade screen I get:

TemplateFile: Method WireHttp::setTimeout does not exist or is not callable in this context<pre>#0 /home/www-data/dev.sev-online.ch/site/modules/ProcessWireUpgrade/ProcessWireUpgradeCheck.module(269): Wire->__call('setTimeout', Array) #1 /home/www-data/dev.sev-online.ch/site/modules/ProcessWireUpgrade/ProcessWireUpgradeCheck.module(269): WireHttp->setTimeout(4.5) #2 /home/www-data/dev.sev-online.ch/site/modules/ProcessWireUpgrade/ProcessWireUpgradeCheck.module(132): ProcessWireUpgradeCheck->getCoreBranches(false) #3 /home/www-data/dev.sev-online.ch/site/modules/ProcessWireUpgrade/ProcessWireUpgrade.module(174): ProcessWireUpgradeCheck->getVersions() #4 /home/www-data/processwire/wire/core/ProcessController.php(196): ProcessWireUpgrade->execute() #5 [internal function]: ProcessController->___execute() #6 /home/www-data/processwire/wire/core/Wire.php(359): call_user_func_array(Array, Array) #7 /home/www-data/processwire/wire/core/Wire.php(317): Wire->runHooks('execute', Array) #8 /home/www-data/processwire/wire/core/admin.php(85): Wire->__call('execute', Array) #9 /home/www-data/processwire/wire/core/admin.php(85): ProcessController->execute() #10 /home/www-data/processwire/wire/modules/AdminTheme/AdminThemeDefault/controller.php(13): require('/home/www-data/...') #11 /home/www-data/dev.sev-online.ch/site/templates/admin.php(32): require('/home/www-data/...') #12 /home/www-data/processwire/wire/core/TemplateFile.php(140): require('/home/www-data/...') #13 [internal function]: TemplateFile->___render() #14 /home/www-data/processwire/wire/core/Wire.php(359): call_user_func_array(Array, Array) #15 /home/www-data/processwire/wire/core/Wire.php(317): Wire->runHooks('render', Array) #16 /home/www-data/processwire/wire/modules/PageRender.module(337): Wire->__call('render', Array) #17 /home/www-data/processwire/wire/modules/PageRender.module(337): TemplateFile->render() #18 [internal function]: PageRender->___renderPage(Object(HookEvent)) #19 /home/www-data/processwire/wire/core/Wire.php(359): call_user_func_array(Array, Array) #20 /home/www-data/processwire/wire/core/Wire.php(317): Wire->runHooks('renderPage', Array) #21 /home/www-data/processwire/wire/core/Wire.php(381): Wire->__call('renderPage', Array) #22 /home/www-data/processwire/wire/core/Wire.php(381): PageRender->renderPage(Object(HookEvent)) #23 /home/www-data/processwire/wire/core/Wire.php(317): Wire->runHooks('render', Array) #24 /home/www-data/processwire/wire/modules/Process/ProcessPageView.module(167): Wire->__call('render', Array) #25 /home/www-data/processwire/wire/modules/Process/ProcessPageView.module(167): Page->render() #26 [internal function]: ProcessPageView->___execute() #27 /home/www-data/processwire/wire/core/Wire.php(359): call_user_func_array(Array, Array) #28 /home/www-data/processwire/wire/core/Wire.php(317): Wire->runHooks('execute', Array) #29 /home/www-data/dev.sev-online.ch/index.php(194): Wire->__call('execute', Array) #30 /home/www-data/dev.sev-online.ch/index.php(194): ProcessPageView->execute() #31 {main}</pre>

**Comment by somatonic** [comment]
At least you should remove the info for requirement on the module page, cause it's not working in 2.4.
